=== rsugio/karlutka/src/test/resources/pi_PerformanceDataQuery/PerformanceDataQuery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified">

    <xs:element name="PerformanceDataQueryResults"
    	type="PerformanceDataQueryResultsType">
    </xs:element>

    <xs:complexType name="PerformanceDataQueryResultsType">
    	<xs:sequence>
    		<xs:element name="Result" type="ResultsType" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="UsageTypes" type="UsageTypesType" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="XIComponents" type="XIComponentsType" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="Views" type="ViewsType" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="Periods" type="PeriodsType" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="Data" type="DataType" maxOccurs="1" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="ResultsType">
    	<xs:sequence>
    		<xs:element name="Code" maxOccurs="1" minOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:enumeration value="OK"></xs:enumeration>
    					<xs:enumeration value="MISSING_PARAM"></xs:enumeration>
    					<xs:enumeration value="APPLICATION_ERROR"></xs:enumeration>
    					<xs:enumeration value="CONNECTION_ERROR"></xs:enumeration>
    					<xs:enumeration value="COMPONENT_NOT_FOUND"></xs:enumeration>
    					<xs:enumeration value="VIEW_NOT_FOUND"></xs:enumeration>
    					<xs:enumeration value="PERIOD_NOT_FOUND"></xs:enumeration>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="Details" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="Text" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="Component" type="xs:string" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="PeriodType" type="xs:string" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="BeginTime" type="xs:string" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="EndTime" type="xs:string" maxOccurs="1" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="UsageTypesType">
    	<xs:sequence>
    		<xs:element name="Usage" type="UsageType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="UsageType">
    	<xs:sequence>
    		<xs:element name="URL" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="Description" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>


    <xs:complexType name="XIComponentsType">
    	<xs:sequence>
    		<xs:element name="Component" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="ViewsType">
    	<xs:sequence>
    		<xs:element name="View" type="ViewType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="PeriodsType">
    	<xs:sequence>
    		<xs:element name="Period" type="PeriodType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    


    <xs:complexType name="ViewType">
    	<xs:sequence>
    		<xs:element name="NameKey" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="LocalizedName" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="PeriodType">
    	<xs:sequence>
    		<xs:element name="Type" maxOccurs="1" minOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:enumeration value="MINUTE"></xs:enumeration>
    					<xs:enumeration value="HOURLY"></xs:enumeration>
    					<xs:enumeration value="DAILY"></xs:enumeration>
    					<xs:enumeration value="WEEKLY"></xs:enumeration>
    					<xs:enumeration value="MONTHLY"></xs:enumeration>
    					<xs:enumeration value="ANNUALLY"></xs:enumeration>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="Interval" type="IntervalType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="IntervalType">
    	<xs:sequence>
    		<xs:element name="Begin" type="xs:dateTime" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="End" type="xs:dateTime" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="DataType">
    	<xs:sequence>
    		<xs:element name="ColumnNames" type="ColumnNamesType" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="DataRows" type="DataRowsType" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="ColumnNamesType">
    	<xs:sequence>
    		<xs:element name="Column" type="xs:string" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="DataRowsType">
    	<xs:sequence>
    		<xs:element name="Row" type="RowType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="RowType">
    	<xs:sequence>
    		<xs:element name="Entry" type="xs:string" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

</xs:schema>

=== rsugio/karlutka/sapapi/src/test/resources/pi_PerformanceDataQuery/01empty.xml
<?xml version="1.0" encoding="UTF-8" ?>
<PerformanceDataQueryResults xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://host:50000/mdt/monitor/PerformanceDataQuery.xsd">
	<Result>
		<Code>MISSING_PARAM</Code>
		<Details>component</Details>
		<Text>No&#x20;PI&#x20;Component&#x20;name&#x20;supplied.</Text>
	</Result>
	<UsageTypes>
		<Usage>
			<URL>http://host:50000/mdt/performancedataqueryservlet</URL>
			<Description>Overview over available PI Components.</Description>
		</Usage>
		<Usage>
			<URL>http://host:50000/mdt/performancedataqueryservlet?component=&lt;PIComponentName&gt;</URL>
			<Description>Request the Performance metadata of a PI Component.</Description>
		</Usage>
		<Usage>
			<URL>http://host:50000/mdt/performancedataqueryservlet?component=&lt;PIComponentName&gt;&amp;begin=&lt;IntervalBeginTime&gt;&amp;end=&lt;IntervalEndTime&gt;</URL>
			<Description>Request the Performance data of a PI Component for the specified view and time interval.</Description>
		</Usage>
	</UsageTypes>
	<XIComponents>
		<Component>af.sid.db0</Component>
		<Component>af.sid.db1</Component>
		<Component>af.sid.db2</Component>
	</XIComponents>

</PerformanceDataQueryResults>
