=== rsugio/karlutka/src/test/resources/pi_ChannelAdmin/ChannelAdmin.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- $Id$ -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="ChannelAdminResult" type="ChannelsType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">The result of a "start" or "stop" action.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="ChannelStatusResult" type="ChannelsType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">The result of a "status" action.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="ErrorInformation" type="ErrorInformationType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				Provides information about a fatal error encountered while executing a request.
			</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="ChannelsType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">A set of channels.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Channels">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="Channel" maxOccurs="unbounded" type="ChannelType" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ChannelType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				Provides information about a channel identified by its party, service and channel name. For the
				"status" action the channel's status is returned in addition to its activation state (whether
				it is started or stopped) while for the "start" and "stop" action, only the new activation
				state is returned. If starting or stopping the channel was not successful, additional
				information is provided inside the AdminErrorInformation element.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Party" type="xsd:string" />
			<xsd:element name="Service" type="xsd:string" />
			<xsd:element name="ChannelName" type="xsd:string" />
			<xsd:element name="ChannelID" type="GUIDType" />
			<xsd:element name="AdapterType" type="xsd:string" />
			<xsd:element name="Direction" type="DirectionType" />
			<xsd:element name="ActivationState"
				type="ActivationStateType" />
			<xsd:element name="ChannelState" type="ChannelStateType"
				minOccurs="0" />
			<xsd:element name="Control" type="AutomationStateType" />
			<xsd:element name="ShortLog" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="AdminErrorInformation" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="ProcessLog" maxOccurs="1" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="LogEntry" maxOccurs="unbounded" minOccurs="0">
                            <xsd:complexType>

                            	<xsd:sequence>
                            		<xsd:element name="Time"
                            			type="xsd:string" maxOccurs="1" minOccurs="1">
                            		</xsd:element>
                            		<xsd:element name="Node"
                            			type="xsd:string" maxOccurs="1" minOccurs="1">
                            		</xsd:element>
                            		<xsd:element name="Status"
                            			type="xsd:string" maxOccurs="1" minOccurs="1">
                            		</xsd:element>
                            		<xsd:element name="MessageKey"
                            			type="xsd:string" maxOccurs="1" minOccurs="1">
                            		</xsd:element>
                            		<xsd:element name="Text"
                            			type="xsd:string" maxOccurs="1" minOccurs="1">
                            		</xsd:element>
                            	</xsd:sequence>
                            </xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="AdminHistory" maxOccurs="1" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="AdminEntry" maxOccurs="unbounded" minOccurs="0">
                            <xsd:complexType>
                            	<xsd:sequence>
                            		<xsd:element name="Time" type="xsd:string" maxOccurs="1" minOccurs="1"/>
                            		<xsd:element name="User" type="xsd:string" maxOccurs="1" minOccurs="1"/>
                            		<xsd:element name="Action" type="xsd:string" maxOccurs="1" minOccurs="1"/>
                            		<xsd:element name="AdminErrors" maxOccurs="1" minOccurs="1">
										<xsd:complexType>
			                            	<xsd:sequence>
			                            		<xsd:element name="ErrorEntry" maxOccurs="unbounded" minOccurs="0">
			                            			<xsd:complexType>
			                            				<xsd:sequence>
						                            		<xsd:element name="Time" type="xsd:string" maxOccurs="1" minOccurs="1"/>
						                            		<xsd:element name="Node" type="xsd:string" maxOccurs="1" minOccurs="1"/>
						                            		<xsd:element name="ErrorInfo" type="xsd:string" maxOccurs="1" minOccurs="1"/>
														</xsd:sequence>
			                            			</xsd:complexType>
			                            		</xsd:element>
			                            	</xsd:sequence>
			                            </xsd:complexType>
                                    </xsd:element>
                            	</xsd:sequence>
                            </xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ErrorInformationType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				Provides information about a fatal error encountered while executing a request.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Exception" type="xsd:string" minOccurs="0" />
			<xsd:element name="Usage" type="xsd:string" minOccurs="0" />
			<xsd:element name="Description" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="GUIDType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9A-Fa-f]{32}" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ActivationStateType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				Identifies the activation state of a channel, i.e., whether it is started or stopped.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="STARTED" />
			<xsd:enumeration value="STOPPED" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ChannelStateType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				Identifies the state of a channel, i.e., whether it is running or in error.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ERROR" />
			<xsd:enumeration value="OK" />
			<xsd:enumeration value="INACTIVE" />
			<xsd:enumeration value="UNKNOWN" />
			<xsd:enumeration value="UNREGISTERED" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AutomationStateType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				Identifies the automation state of a channel. Possible values: MANUAL (channel started and stopped manually from the Communication Channel Monitor tool), SCHEDULER (channel started and stopped automatically by the Adapter Framework according to Availability Time plans) and  WEBSERVICE ((channel started and stopped from external source by a call to the /AdapterFramework/ChannelAdminServlet)
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="MANUAL" />
			<xsd:enumeration value="SCHEDULER" />
			<xsd:enumeration value="WEBSERVICE" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DirectionType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				Identifies the direction of a channel. Possible values: INBOUND (Sender Channel) and OUTBOUND (Receiver Channel).
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="INBOUND" />
			<xsd:enumeration value="OUTBOUND" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== rsugio/karlutka/src/test/resources/pi_ChannelAdmin/02list.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--DOCTYPE ChannelStatusResult SYSTEM "/AdapterFramework/channelAdmin/ChannelAdmin.dtd"-->
<ChannelStatusResult xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ChannelAdmin.xsd">
	<Channels>
		<Channel>
			<Party/>
			<Service>BS_ECM_ZZZ</Service>
			<ChannelName>CC_RESTSender_ProjectContractLimitCheck</ChannelName>
			<ChannelID>5d7c82087c0a3ca28465a5684396b023</ChannelID>
			<AdapterType>REST</AdapterType>
			<Direction>INBOUND</Direction>
			<ActivationState>STARTED</ActivationState>
			<ChannelState>ERROR</ChannelState>
			<Control>SCHEDULER</Control>
			<ShortLog>
				<![CDATA[Server 00 00_49912 : Error: Configuration table Custom XML/JSON Conversion Rules has an invalid value in row 2. Parameter Array Type does not contain a valid boolean expression.]]>
			</ShortLog>
			<ProcessLog/>
			<AdminHistory>
				<AdminEntry>
					<Time>13.08.2022 04:34:59 UTC</Time>
					<User>123</User>
					<Action>STARTED</Action>
					<AdminErrors/>
				</AdminEntry>
				<AdminEntry>
					<Time>13.08.2022 04:34:58 UTC</Time>
					<User>123</User>
					<Action>STOPPED</Action>
					<AdminErrors/>
				</AdminEntry>
			</AdminHistory>
		</Channel>
		<Channel>
			<Party/>
			<Service>1212</Service>
			<ChannelName>CC_123</ChannelName>
			<ChannelID>c181f5900ebe31cdad96471da9684fc0</ChannelID>
			<AdapterType>JDBC</AdapterType>
			<Direction>INBOUND</Direction>
			<ActivationState>STARTED</ActivationState>
			<ChannelState>OK</ChannelState>
			<Control>MANUAL</Control>
			<ProcessLog>
				<LogEntry>
					<Time>13.08.2022 04:05:43 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey>b054f2f3197e11ed933f0000004c2912&#x28;OUTBOUND&#x29;</MessageKey>
					<Text>Processing&#x20;finished&#x20;successfully</Text>
				</LogEntry>
				<LogEntry>
					<Time>13.08.2022 04:05:43 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey/>
					<Text>Processing&#x20;started</Text>
				</LogEntry>
				<LogEntry>
					<Time>13.08.2022 03:05:43 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey>b054f2f3197e11ed933f0000004c2912&#x28;OUTBOUND&#x29;</MessageKey>
					<Text>Processing&#x20;finished&#x20;successfully</Text>
				</LogEntry>
				<LogEntry>
					<Time>13.08.2022 03:05:43 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey/>
					<Text>Processing&#x20;started</Text>
				</LogEntry>
				<LogEntry>
					<Time>13.08.2022 02:05:43 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey>b054f2f3197e11ed933f0000004c2912&#x28;OUTBOUND&#x29;</MessageKey>
					<Text>Processing&#x20;finished&#x20;successfully</Text>
				</LogEntry>
			</ProcessLog>
			<AdminHistory/>
		</Channel>
		<Channel>
			<Party/>
			<Service>BS_ZZZ</Service>
			<ChannelName>CC_Voyage</ChannelName>
			<ChannelID>07c5226ce9f930769fa610eae5584755</ChannelID>
			<AdapterType>REST</AdapterType>
			<Direction>OUTBOUND</Direction>
			<ActivationState>STARTED</ActivationState>
			<ChannelState>OK</ChannelState>
			<Control>SCHEDULER</Control>
			<ProcessLog>
				<LogEntry>
					<Time>09.08.2022 11:21:03 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey>005056bf-8d88-1eed-85fa-ab2a69df2212&#x28;INBOUND&#x29;</MessageKey>
					<Text>Message&#x20;processing&#x20;completed&#x20;successfully</Text>
				</LogEntry>
				<LogEntry>
					<Time>09.08.2022 11:21:03 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey>005056bf-8d88-1eed-85fa-ab2a69df2212&#x28;INBOUND&#x29;</MessageKey>
					<Text>Message&#x20;sent&#x20;to&#x20;external&#x20;server</Text>
				</LogEntry>
				<LogEntry>
					<Time>09.08.2022 11:21:01 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey>005056bf-8d88-1eed-85fa-ab2a69df2212&#x28;INBOUND&#x29;</MessageKey>
					<Text>Start&#x20;processing&#x20;outbound&#x20;message</Text>
				</LogEntry>
				<LogEntry>
					<Time>09.08.2022 11:21:01 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey>005056bf-8d88-1eed-85fa-ab2a69df2212&#x28;INBOUND&#x29;</MessageKey>
					<Text>Message&#x20;processing&#x20;started</Text>
				</LogEntry>
				<LogEntry>
					<Time>09.08.2022 11:21:00 UTC</Time>
					<Node>Server 00 00_49912</Node>
					<Status>OK</Status>
					<MessageKey>005056bf-8d88-1eed-85fa-ab02b7ea8212&#x28;INBOUND&#x29;</MessageKey>
					<Text>Message&#x20;sent&#x20;to&#x20;external&#x20;server</Text>
				</LogEntry>
			</ProcessLog>
			<AdminHistory>
				<AdminEntry>
					<Time>20.06.2022 08:42:08 UTC</Time>
					<User>123</User>
					<Action>STARTED</Action>
					<AdminErrors/>
				</AdminEntry>
				<AdminEntry>
					<Time>25.03.2022 13:45:54 UTC</Time>
					<User>123</User>
					<Action>STOPPED</Action>
					<AdminErrors>
						<ErrorEntry>
							<Time>1</Time>
							<Node>2</Node>
							<ErrorInfo>3</ErrorInfo>
						</ErrorEntry>
					</AdminErrors>
				</AdminEntry>
			</AdminHistory>

		</Channel>
	</Channels>
</ChannelStatusResult>

=== rsugio/karlutka/src/test/resources/pi_ChannelAdmin/04stop.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ChannelAdminResult SYSTEM "/AdapterFramework/channelAdmin/ChannelAdmin.dtd">
<ChannelAdminResult xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://LD-S-TSTzzz:50000/AdapterFramework/channelAdmin/ChannelAdmin.xsd">
	<Channels>
		<Channel>
			<Party></Party>
			<Service>BC_TEST1</Service>
			<ChannelName>qqqq</ChannelName>
			<ChannelID>7f07b93433cb31acb93486b222d74d93</ChannelID>
			<AdapterType>REST</AdapterType>
			<Direction>OUTBOUND</Direction>
			<ActivationState>STOPPED</ActivationState>
			<Control>WEBSERVICE</Control>
			<ShortLog><![CDATA[Server 00 00_49912 : Channel stopped]]></ShortLog>
		</Channel>
	</Channels>
</ChannelAdminResult>

=== rsugio/karlutka/src/test/resources/pi_ChannelAdmin/01list.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ChannelStatusResult SYSTEM "/AdapterFramework/channelAdmin/ChannelAdmin.dtd">
<ChannelStatusResult xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://host:50000/AdapterFramework/channelAdmin/ChannelAdmin.xsd">
    <Channels>
        <Channel>
            <Party>P_1C</Party>
            <Service>BS</Service>
            <ChannelName>CC_SOAPReceiver_ASOP_EmployeeInformation</ChannelName>
            <ChannelID>3d7c1402a1923383837d986dee3ea4e1</ChannelID>
            <AdapterType>SOAP</AdapterType>
            <Direction>OUTBOUND</Direction>
            <ActivationState>STARTED</ActivationState>
            <ChannelState>OK</ChannelState>
            <Control>SCHEDULER</Control>
        </Channel>
        <Channel>
            <Party></Party>
            <Service>BS2</Service>
            <ChannelName>CC_SOAPReceiver_SalesOrderRequest</ChannelName>
            <ChannelID>77b98eceabc43d6a81f8271814e5e0e4</ChannelID>
            <AdapterType>SOAP</AdapterType>
            <Direction>OUTBOUND</Direction>
            <ActivationState>STARTED</ActivationState>
            <ChannelState>OK</ChannelState>
            <Control>SCHEDULER</Control>
        </Channel>
    </Channels>
</ChannelStatusResult>

=== rsugio/karlutka/src/test/resources/pi_ChannelAdmin/03stop.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ChannelAdminResult SYSTEM "/AdapterFramework/channelAdmin/ChannelAdmin.dtd">
<ChannelAdminResult xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://H:50000/AdapterFramework/channelAdmin/ChannelAdmin.xsd">
    <Channels>
        <Channel>
            <Party></Party>
            <Service>BC_TEST1</Service>
            <ChannelName>qqqq</ChannelName>
            <ChannelID>7f07b93433cb31acb93486b222d74d93</ChannelID>
            <AdapterType>REST</AdapterType>
            <Direction>OUTBOUND</Direction>
            <ActivationState>STARTED</ActivationState>
            <ChannelState>OK</ChannelState>
            <Control>SCHEDULER</Control>
            <AdminErrorInformation>com.sap.aii.af.service.administration.impl.WrongAutomationModeException&#x3a;&#x20;The&#x20;channel&#x20;&quot;&#x2f;BC_TEST1&#x2f;qqqq&#x20;&#x28;GUID&#x20;7f07b93433cb31acb93486b222d74d93&#x29;&quot;&#x20;is&#x20;configured&#x20;to&#x20;use&#x20;an&#x20;automation&#x20;mode&#x20;not&#x20;compatible&#x20;with&#x20;the&#x20;type&#x20;of&#x20;the&#x20;current&#x20;principal&#x20;&#x28;WSUSER&#x29;.&#x20;The&#x20;channel&#x20;was&#x20;not&#x20;stopped.&#x20;Change&#x20;the&#x20;channels&#x20;automation&#x20;mode&#x20;and&#x20;repeat&#x20;the&#x20;administrative&#x20;action.&#xa;&#x9;at&#x20;com.sap.aii.af.service.administration.impl.AdminManagerImpl.setChannelActivationState&#x28;AdminManagerImpl.java&#x3a;998&#x29;&#xa;&#x9;at&#x20;com.sap.aii.af.service.administration.impl.AdminManagerImpl.setChannelActivationState&#x28;AdminManagerImpl.java&#x3a;838&#x29;&#xa;&#x9;at&#x20;com.sap.aii.af.app.administration.scheduling.SchedulingServlet.doGet&#x28;SchedulingServlet.java&#x3a;229&#x29;&#xa;&#x9;at&#x20;javax.servlet.http.HttpServlet.service&#x28;HttpServlet.java&#x3a;734&#x29;&#xa;&#x9;at&#x20;javax.servlet.http.HttpServlet.service&#x28;HttpServlet.java&#x3a;847&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.servlets_jsp.server.Invokable.invoke&#x28;Invokable.java&#x3a;152&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.servlets_jsp.server.Invokable.invoke&#x28;Invokable.java&#x3a;38&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.servlets_jsp.server.HttpHandlerImpl.runServlet&#x28;HttpHandlerImpl.java&#x3a;466&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.servlets_jsp.server.HttpHandlerImpl.handleRequest&#x28;HttpHandlerImpl.java&#x3a;210&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.server.RequestAnalizer.startServlet&#x28;RequestAnalizer.java&#x3a;439&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.server.RequestAnalizer.startServlet&#x28;RequestAnalizer.java&#x3a;428&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.servlets_jsp.filters.DSRWebContainerFilter.process&#x28;DSRWebContainerFilter.java&#x3a;38&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.servlets_jsp.filters.ServletSelector.process&#x28;ServletSelector.java&#x3a;81&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.servlets_jsp.filters.ApplicationSelector.process&#x28;ApplicationSelector.java&#x3a;278&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.filters.WebContainerInvoker.process&#x28;WebContainerInvoker.java&#x3a;85&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.HostFilter.process&#x28;HostFilter.java&#x3a;9&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.filters.ResponseLogWriter.process&#x28;ResponseLogWriter.java&#x3a;60&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.HostFilter.process&#x28;HostFilter.java&#x3a;9&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.filters.DefineHostFilter.process&#x28;DefineHostFilter.java&#x3a;27&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.ServerFilter.process&#x28;ServerFilter.java&#x3a;12&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.filters.MonitoringFilter.process&#x28;MonitoringFilter.java&#x3a;29&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.ServerFilter.process&#x28;ServerFilter.java&#x3a;12&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.filters.SessionSizeFilter.process&#x28;SessionSizeFilter.java&#x3a;26&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.ServerFilter.process&#x28;ServerFilter.java&#x3a;12&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.filters.MemoryStatisticFilter.process&#x28;MemoryStatisticFilter.java&#x3a;57&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.ServerFilter.process&#x28;ServerFilter.java&#x3a;12&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.filters.DSRHttpFilter.process&#x28;DSRHttpFilter.java&#x3a;43&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.ServerFilter.process&#x28;ServerFilter.java&#x3a;12&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.chain.AbstractChain.process&#x28;AbstractChain.java&#x3a;78&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.server.Processor.chainedRequest&#x28;Processor.java&#x3a;468&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.server.Processor&#x24;FCAProcessorThread.process&#x28;Processor.java&#x3a;262&#x29;&#xa;&#x9;at&#x20;com.sap.engine.services.httpserver.server.rcm.RequestProcessorThread.run&#x28;RequestProcessorThread.java&#x3a;56&#x29;&#xa;&#x9;at&#x20;com.sap.engine.core.thread.execution.Executable.run&#x28;Executable.java&#x3a;122&#x29;&#xa;&#x9;at&#x20;com.sap.engine.core.thread.execution.Executable.run&#x28;Executable.java&#x3a;101&#x29;&#xa;&#x9;at&#x20;com.sap.engine.core.thread.execution.CentralExecutor&#x24;SingleThread.run&#x28;CentralExecutor.java&#x3a;328&#x29;&#xa;</AdminErrorInformation>
        </Channel>
    </Channels>
</ChannelAdminResult>
